name: Android preview build

on:
  pull_request:
    branches: [develop]
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  build_android_preview:
    name: Build Android preview APK
    type: build
    params:
      platform: android
      profile: preview
