import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { Screen, LoadingState } from "@/components/Screen";
import { SearchBox } from "@/components/SearchBox";
import { colors, radius, spacing } from "@/constants/theme";
import { ResourceEmpty, ResourceError } from "@/features/shared/ResourceStates";
import { formatCurrency, formatDate, joinMeta } from "@/utils/format";
import type { InventoryProduct } from "@/types";
import { useInventory } from "./useInventory";

export function InventoryScreen({ alerts = false }: { alerts?: boolean }) {
  const { error, items, loading, movements, search, setSearch, summary } = useInventory(alerts);
  if (loading && !items.length) return <LoadingState />;
  return <Screen>
    <View style={styles.hero}><View><Text style={styles.eyebrow}>Smart stock control</Text><Text style={styles.heroTitle}>{alerts ? "Stock alerts" : "Inventory"}</Text><Text style={styles.heroText}>{alerts ? "Items at or below their reorder level." : "Live products, stock health and recent movement."}</Text></View><Ionicons color="#c4b5fd" name={alerts ? "alert-circle" : "cube"} size={44} /></View>
    {summary ? <View style={styles.stats}><Stat label="Products" value={summary.products} /><Stat label="In stock" value={summary.total_stock} /><Stat danger={summary.low_stock > 0} label="Low stock" value={summary.low_stock} /><Stat danger={summary.out_of_stock > 0} label="Out" value={summary.out_of_stock} /></View> : null}
    {!alerts && summary ? <Text style={styles.value}>Stock value  {formatCurrency(summary.stock_value)}</Text> : null}
    {!alerts ? <Pressable onPress={() => router.push("/(tabs)/inventory-alerts")} style={styles.alertLink}><Ionicons color="#ea580c" name="warning" size={20} /><View style={{ flex: 1 }}><Text style={styles.alertTitle}>Needs attention</Text><Text style={styles.muted}>{summary?.low_stock ?? 0} low and {summary?.out_of_stock ?? 0} out of stock</Text></View><Ionicons color={colors.muted} name="chevron-forward" size={18} /></Pressable> : null}
    <SearchBox value={search} onChangeText={setSearch} placeholder="Search products, categories or suppliers" />
    <ResourceError message={error} />
    <Text style={styles.heading}>{alerts ? "Items to replenish" : "Products"}</Text>
    {items.length ? items.map(item => <ProductCard item={item} key={item.id} />) : <ResourceEmpty text={alerts ? "All stock levels look healthy." : "No inventory products found."} />}
    {!alerts && movements.length ? <><Text style={styles.heading}>Recent movement</Text>{movements.slice(0, 5).map(item => <View key={item.id} style={styles.movement}><View style={styles.movementIcon}><Ionicons color={item.quantity < 0 ? colors.danger : colors.success} name={item.quantity < 0 ? "arrow-down" : "arrow-up"} size={16} /></View><View style={{ flex: 1 }}><Text style={styles.cardTitle}>{item.product_name}</Text><Text style={styles.muted}>{joinMeta([item.movement_label, item.reference, formatDate(item.created_at)])}</Text></View><Text style={[styles.quantity, { color: item.quantity < 0 ? colors.danger : colors.success }]}>{item.quantity > 0 ? "+" : ""}{item.quantity}</Text></View>)}</> : null}
  </Screen>;
}

function Stat({ danger, label, value }: { danger?: boolean; label: string; value: number }) { return <View style={styles.stat}><Text style={[styles.statValue, danger && { color: colors.danger }]}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
function ProductCard({ item }: { item: InventoryProduct }) { const danger = item.stock_status !== "In stock"; return <View style={styles.card}><View style={styles.cardTop}><View style={{ flex: 1 }}><Text style={styles.cardTitle}>{item.name}</Text><Text style={styles.muted}>{joinMeta([item.sku, item.category_name, item.supplier_name])}</Text></View><View style={[styles.badge, { backgroundColor: danger ? "#fff7ed" : "#ecfdf5" }]}><Text style={{ color: danger ? "#c2410c" : colors.success, fontSize: 9, fontWeight: "900" }}>{item.stock_status}</Text></View></View><View style={styles.cardBottom}><Text style={styles.price}>{formatCurrency(item.price)}</Text><Text style={[styles.stock, danger && { color: colors.danger }]}>{item.stock_on_hand} units</Text></View></View>; }

const styles = StyleSheet.create({
  alertLink: { alignItems: "center", backgroundColor: "#fff7ed", borderColor: "#fed7aa", borderRadius: radius.lg, borderWidth: 1, flexDirection: "row", gap: spacing.md, marginBottom: spacing.md, padding: spacing.md }, alertTitle: { color: "#9a3412", fontSize: 13, fontWeight: "900" }, badge: { borderRadius: 999, paddingHorizontal: spacing.sm, paddingVertical: 6 }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg, borderWidth: 1, marginBottom: spacing.sm, padding: spacing.md }, cardBottom: { alignItems: "center", borderTopColor: "#eef2f7", borderTopWidth: 1, flexDirection: "row", justifyContent: "space-between", marginTop: spacing.md, paddingTop: spacing.sm }, cardTitle: { color: colors.text, fontSize: 14, fontWeight: "900" }, cardTop: { alignItems: "flex-start", flexDirection: "row", gap: spacing.sm }, eyebrow: { color: "#c4b5fd", fontSize: 9, fontWeight: "900", letterSpacing: 1, textTransform: "uppercase" }, heading: { color: colors.text, fontSize: 16, fontWeight: "900", marginBottom: spacing.sm, marginTop: spacing.md }, hero: { alignItems: "center", backgroundColor: "#4c1d95", borderRadius: radius.lg, flexDirection: "row", justifyContent: "space-between", marginBottom: spacing.md, marginTop: spacing.sm, padding: spacing.lg }, heroText: { color: "#ddd6fe", fontSize: 11, marginTop: 4, maxWidth: 230 }, heroTitle: { color: "white", fontSize: 23, fontWeight: "900", marginTop: 2 }, movement: { alignItems: "center", backgroundColor: colors.surface, borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: "row", gap: spacing.sm, padding: spacing.md }, movementIcon: { alignItems: "center", backgroundColor: "#f8fafc", borderRadius: 10, height: 34, justifyContent: "center", width: 34 }, muted: { color: colors.muted, fontSize: 10, lineHeight: 14, marginTop: 2 }, price: { color: colors.text, fontSize: 13, fontWeight: "900" }, quantity: { fontSize: 13, fontWeight: "900" }, stat: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, flex: 1, minWidth: 70, padding: spacing.sm }, statLabel: { color: colors.muted, fontSize: 8, fontWeight: "800", marginTop: 2, textTransform: "uppercase" }, stats: { flexDirection: "row", gap: spacing.xs, marginBottom: spacing.sm }, statValue: { color: colors.primaryDark, fontSize: 17, fontWeight: "900" }, stock: { color: colors.success, fontSize: 11, fontWeight: "900" }, value: { color: colors.muted, fontSize: 11, fontWeight: "800", marginBottom: spacing.md, textAlign: "right" }
});
